In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2 # vectorized operation (this is used c language and c lan. is already fast than python)
result

array([ 1,  4,  9, 16, 25])

In [4]:
result + 10

array([11, 14, 19, 26, 35])

In [5]:
arr1 = np.array([[1, 2, 4],[5, 6, 7]])
arr2 = np.array([1, 2, 3])
result = arr1 + arr2 
result

array([[ 2,  4,  7],
       [ 6,  8, 10]])

In [6]:
# normalization
data = np.array([[10, 20, 30],
                [15,25,35],
                [20, 30 ,40],
                [25,35 , 40],
                [30, 40, 50]])

mean = data.mean(axis = 0)
std = data.std(axis = 0)

normalized = (data - mean) / std

normalized

array([[-1.41421356, -1.41421356, -1.35680105],
       [-0.70710678, -0.70710678, -0.60302269],
       [ 0.        ,  0.        ,  0.15075567],
       [ 0.70710678,  0.70710678,  0.15075567],
       [ 1.41421356,  1.41421356,  1.6583124 ]])