In [1]:
import numpy as np

In [2]:
# 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [3]:
# 2D array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [4]:
# type and shape
print(type(arr1))
print(type(arr2))

print(arr2.shape)
print(arr1.shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(2, 3)
(5,)


In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0, 12, 4)

array([ 0.,  4.,  8., 12.])

## 2. Checking array properties

In [11]:
utsav = np.array([[1,2,3],[4,5,6]])

In [12]:
utsav.shape

(2, 3)

In [13]:
utsav.size

6

In [14]:
utsav.ndim

2

In [15]:
utsav.dtype

dtype('int64')

## 3. Changing Data Type

In [24]:
krishna = np.array([1,2,3])

In [25]:
krishna.dtype

dtype('int64')

In [28]:
krishna1 = np.array([1,2,3], dtype ='float32')
# or krishna1 = np.array([1,2,3], dtype = np.float32)
krishna1.dtype

dtype('float32')

In [29]:
# જ્યારે વેરિએબલ પહેલેથી જ બનાવેલ હોય અને તેના ડેટાટાઈપ માં ફેરફાર કરવો હોય ત્યારે:
krishna1_int = krishna1.astype(np.int32)
print(krishna1_int)

[1 2 3]


## 4. Reshaping and Flattening Arrays

In [20]:
radhe = np.array([[1,2,3],[4,5,6]])
radhe.shape

(2, 3)

In [21]:
reshaped = radhe.reshape(3, 2)

In [22]:
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
flattened = radhe.flatten()
flattened

array([1, 2, 3, 4, 5, 6])