# Indexing

In [1]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [4]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
flat = arr.flatten()

In [6]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
flat[0]

np.int64(1)

In [9]:
flat[3: 8]

array([4, 5, 6, 7, 8])

In [14]:
flat[: 3] #Same As flat[0:5]

array([1, 2, 3])

In [16]:
flat[3:] #Same As flat[0:13]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

# Slicing

In [17]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
b = flat[3: 7].copy()

In [24]:
b

array([44,  5,  6,  7])

In [25]:
b[0] = 46

In [26]:
flat

array([ 1,  2,  3, 44,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
b

array([46,  5,  6,  7])

In [30]:
arr = np.array([1,54,53,42,2,3,34,5,6])

In [31]:
arr[[1,4,6]]

array([54,  2, 34])

In [32]:
arr[arr>23]

array([54, 53, 42, 34])

# Exercise

- Create A 3 x 3 array filled with random numbers and print its shape.

In [33]:
utsav = np.full((3,3), 6)

In [34]:
utsav

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [35]:
utsav.shape

(3, 3)

- Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [38]:
radhe = np.array([1.1, 2.2, 3.3], dtype = 'int64')

In [39]:
radhe

array([1, 2, 3])

In [40]:
radhe.dtype

dtype('int64')

- Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

In [41]:
krishn = np.array([1, 2, 3, 4, 5, 6])

In [42]:
krishn

array([1, 2, 3, 4, 5, 6])

In [44]:
krishn[[1,3,5]]

array([2, 4, 6])

- Reshape a 1D array of Size 9 into a 3 x 3 Matrix.

In [45]:
kanha = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
kanha

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
reshaped = kanha.reshape(3, 3)

In [48]:
reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])