In [1]:
import numpy as np

In [2]:
arr = np.array([12, 4, 18, 3, 4])

In [3]:
arr

array([12,  4, 18,  3,  4])

In [4]:
np.mean(arr)

np.float64(8.2)

In [5]:
np.std(arr)

np.float64(5.878775382679627)

In [6]:
np.var(arr)

np.float64(34.559999999999995)

In [7]:
np.min(arr)

np.int64(3)

In [8]:
np.max(arr)

np.int64(18)

In [9]:
np.sum(arr)

np.int64(41)

In [10]:
np.prod(arr) # give us product of all element means all element *(multiplication).

np.int64(10368)

In [11]:
np.median(arr)

np.float64(4.0)

In [12]:
np.percentile(arr, 10) # for the 10th percentile (median) 

np.float64(3.4)

In [13]:
np.argmin(arr) # give us a index of the minimum value in an array.

np.int64(3)

In [14]:
np.argmax(arr) # give us a index of the maximun value in an array.

np.int64(2)

In [15]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

np.corrcoef(arr1, arr2) # give us correlation coefficient of an array

array([[1., 1.],
       [1., 1.]])

In [16]:
np.unique(arr)

array([ 3,  4, 12, 18])

In [17]:
np.diff(arr) # give us difference between next element and corrent element.

array([ -8,  14, -15,   1])

In [18]:
np.cumsum(arr) # give us cumulative sum.

array([12, 16, 34, 37, 41])

In [19]:
np.linspace(4, 16, 4) #give us 4 elements from 4 to 16. 

array([ 4.,  8., 12., 16.])

In [20]:
np.log(arr) # compute the natural logarithm of array.

array([2.48490665, 1.38629436, 2.89037176, 1.09861229, 1.38629436])

In [21]:
np.exp(arr) # compute the exponential of an array.

array([1.62754791e+05, 5.45981500e+01, 6.56599691e+07, 2.00855369e+01,
       5.45981500e+01])