In [1]:
import numpy as np

In [2]:
arr = np.array([16,7,3,16])

In [3]:
arr.dtype

dtype('int64')

In [4]:
arr.astype('float64')

array([16.,  7.,  3., 16.])

In [5]:
arr2 = np.array([16,4,9,43], dtype = "float32")

In [6]:
arr2

array([16.,  4.,  9., 43.], dtype=float32)

In [9]:
arr.nbytes  #this array occupy 32 bytes bcz that have 4 element,and that int64 types use 8 bytes per element.

32

In [10]:
arr2.nbytes    #this array occupy 16 bytes bcz that have 4 element,and that float32 types use 4 bytes per element.

16

In [11]:
arr = np.array(['apple','banana','cherry'], dtype = 'U10')
arr

array(['apple', 'banana', 'cherry'], dtype='<U10')

In [12]:
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype = 'complex128')
arr

array([1.+2.j, 3.+4.j, 5.+6.j])

In [13]:
arr = np.array([{'a': 1},[1, 2, 3], 'hello'], dtype = object)
arr

array([{'a': 1}, list([1, 2, 3]), 'hello'], dtype=object)